# This file contains the credentials for the voice & chat platforms
# which your bot is using.
# https://rasa.com/docs/rasa/user-guide/messaging-and-voice-channels/

rest:
#  # you don't need to provide anything here - this channel doesn't
#  # require any credentials


facebook:
  verify: "streetcar_delay"
  secret: "adc23d134213a9f30f611d97ad80a8e5"
  page-access-token: "EAAGJJZCYFfXkBAM6cHS63PYmxLK0fZASitS9qRxdF5VOVc8TSbe9z3ZBNt5aHnIKFVblFJWdoJNbfLAUUZBKxZBh6ZCWwmGoEpIH6WwDZAWZBu5y44ZAPU3wdT5xQgJI3ZCoUbvgKdIHVRJgSOecKx3aZBTyaeGzgZCHay2UaiaZBSqoomAZDZD"

#slack:
#  slack_token: "<your slack token>"
#  slack_channel: "<the slack channel>"

#socketio:
#  user_message_evt: <event name for user message>
#  bot_message_evt: <event name for but messages>
#  session_persistence: <true/false>

rasa:
  url: "http://localhost:5002/api"
