general:
   load_from_scratch: False
   save_transformed_dataframe: True
   remove_bad_values: True
file_names:
   pickled_input_dataframe: 2014_2019.pkl
   pickled_output_dataframe: 2014_2019_df_cleaned_remove_bad_values_may16_2020.pkl
   